/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sh_suhe_demos_JniTest */

#ifndef _Included_com_sh_suhe_demos_JniTest
#define _Included_com_sh_suhe_demos_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sh_suhe_demos_JniTest
 * Method:    getCLanguageString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sh_suhe_demos_JniTest_getCLanguageString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
